<html>
    <table>
        <tr>
            <th>no</th>
            <th>no</th>
            <th>no</th>
            <th>no</th>
        </tr>
        <tr>
            <td>1</td>
            <td>1</td>
            <td>1</td>
            <td>1</td>
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td>1</td>
        </tr>
    </table>
</html>